apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-kustomization
  namespace: flux-system
spec:
  interval: 1m
  path: "./"  # Ruta donde están los manifiestos
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-repo
    namespace: flux-system
  validation: client
